default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"].to_s != "" ? ENV["DATABASE_URL"] : "postgresql://localhost/recipe_app_development" %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL_TEST"].to_s != "" ? ENV["DATABASE_URL_TEST"] : "postgresql://localhost/recipe_app_test" %>

production:
  <<: *default
  <% if ENV["DATABASE_URL"].to_s != "" %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  database: recipe_app_production
  <% end %>